version: "3"
services:
  memgraph:
    image: memgraph/memgraph
    container_name: memgraph_3
    user: root
    volumes:
      - ./memgraph/entrypoint:/usr/lib/memgraph/entrypoint
      - ./memgraph/import-data:/usr/lib/memgraph/import-data
      - ./memgraph/mg_lib:/var/lib/memgraph
      - ./memgraph/mg_log:/var/log/memgraph
      - ./memgraph/mg_etc:/etc/memgraph
    ports:
      - "7687:7687"
    entrypoint: ./entrypoint/docker-entrypoint.sh
    environment:
      MG_HOST: memgraph
      MG_PORT: 7687